### ISSUE TITLE
Unexpected behaviour with 'planes' param

### ISSUE THREAD

**Issue by DonCanjas** [Asd-g/AviSynthPlus-NNEDI3CL#11]
Not sure if I'm in the wrong, but I'm expecting the video to be Y8. 
Even if nnedi3cl is intended to keep the planes, it's looking green which I don't really think it's intentional. Using anything besides the default [0, 1, 2, 3] (in this case [0, 1, 2]) will output a weird looking clip.

I'd rather have a 'planes' param that would let me choose to either discard, copy or process a plane like [2, 3, 3, 1] where 1=discard, 2=copy, 3=process. I don't know if there's any specific reason behind [0,1,2,3]. 
It could help simplifying image enlargement for either upscaling or anti-aliasing when you want to process only luma for most of the times, without having to resort to ExtractY().

```c++
ColorBarsHD()
nnedi3cl(field=1, planes=0)
```
![imagem](https://user-images.githubusercontent.com/80267631/224564050-f758817f-bd69-460b-b5ea-088500cc1afe.png)

```c++
ColorBarsHD()
nnedi3cl(field=1, planes=[0, 1, 2])
```
![imagem](https://user-images.githubusercontent.com/80267631/224564607-e90cd445-836f-4dbb-92d4-97a940f2cb29.png)

**Comment by Asd-g** [comment]
> Not sure if I'm in the wrong, but I'm expecting the video to be Y8.
Even if nnedi3cl is intended to keep the planes, it's looking green which I don't really think it's intentional. Using anything besides the default [0, 1, 2, 3] (in this case [0, 1, 2]) will output a weird looking clip.

It's expected. The output format is YUV(A) and any unprocessed plane will contain garbage resulting in a weird output.

Try 1.0.7 with `planes=0, luma=true` and you will get Y only output.
As the name of the new parameter suggests, it's possible to output Y format only for luma plane. If you want a chroma plane use ExtractU/V.

**Comment by DonCanjas** [comment]
Seems to work fine now, would you mind to add that new param to NNEDI3CL_rpow2.avsi too? 
And since we're already mentioning this, would you please add these changes to EEDI3CL as well? I think it'd be annoying for both of us to open a new issue in EEDI3CL's repo just to mention this all over again.

**Comment by Asd-g** [comment]
Done.
